### ISSUE TITLE
Bevezető szöveg véglegesítése

### ISSUE THREAD

**Issue by aboros** [drupalhu/mde#10]
A mostani lorem szöveget végleges kopira kell cserélni.

**Comment by reisingerg** [comment]
Zsófit kértem meg az első verzió elkészítésére

**Comment by csakiistvan** [comment]
Ez mikorra várható?

**Comment by zsofimajor** [comment]
Megúsztam mindennel, sorry, de tudok róla, és rajta van a todo listámon.

**Comment by reisingerg** [comment]
Itt a végleges mission szöveg:

A magyarországi Drupal közösség a Drupal tartalomkezelő rendszer első verzióinak megjelenést követően kezdett el szerveződni, így több, mint 10 éves múltra tekinthet vissza.

A közösség aktív tagjainak kezdeményezése révén az Egyesület 2015-ben megalakult, azzal a célkitűzéssel hogy jogi hátteret és támogatást biztosítson a hazai Drupal közösség szakmai együttműködésének elősegítésére.

Tevékenységünket a Drupal magyarországi népszerűsítése, valamint a magyar Drupal közösség nemzetközi pozíciójának erősítése érdekében kívánjuk végezni.

Céljaink:
- A hazai Drupal közösség építése és bővítése
- A Drupal rendszer ismeretének és használatának népszerűsítése
- Szakmai rendezvények szervezése, támogatása és promótálása
- Hasznosítható szaktudás, oktatás és ismeretterjesztés elősegítése és támogatása

**Comment by tanarurkerem** [comment]
szerintem ez jó. mergelhető, zárható
