### ISSUE TITLE
Twitter accountok a tagoknak

### ISSUE THREAD

**Issue by zsofimajor** [drupalhu/mde#18]
Az elnökségi tagoknál a twitter gombok linkeljenek adott tag twitterére az alábbi lista szerint.

Reisinger Gábor: https://twitter.com/reisingerg
Boros Ádám: https://twitter.com/hunaboros
Csáki István: https://twitter.com/csakiistvan
Dávid Andor: https://twitter.com/andor_david
Major Zsófi: https://twitter.com/zsofimajor
Csonka Gergely: https://twitter.com/gergelycsonka
Pónya Péter: https://twitter.com/pedroleoman
Tompa Gábor: https://twitter.com/tompagabor

**Comment by tanarurkerem** [comment]
Ez szerintem jó. Mergelhető, zárható.
