### ISSUE TITLE
Html fejléc meta tegek véglegesítése

### ISSUE THREAD

**Issue by aboros** [drupalhu/mde#28]
A következő metákat frissíteni kell valós szöveggel és URLekkel.
description
og:url
og:image
og:description

Ezeken kívül teljesen hiányzik a _keywords_ meta. Nincs már nagy jelentősége, de azért ártani nem árt. Javaslat: "Drupal, Magyar Drupal, Drupal Közösség, Drupal Egyesület"

**Comment by reisingerg** [comment]
meta property="og:title" content="Magyar Drupal Egyesület"
meta property="og:site_name" content="Magyar Drupal Egyesület"
meta property="og:description" content="Magyar Drupal Egyesület"
meta property="og:url" content="http://egyesulet.drupal.hu/"

Szerintem nincs értelme túlbonyolítani :)

**Comment by csakiistvan** [comment]
```
<meta property="og:description" content="A Magyar Drupal Egyesület 2015-ben alakult meg, hogy jogi hátteret és támogatást biztosítson a hazai Drupal közösség szakmai együttműködésének.">
```

**Comment by tompagabor** [comment]
Úgy látom, hogy ezeket a meta adatokat már kitöltöttük a kódban.
Nézzetek rá, hogy megfelelő-e, és ha igen, akkor zárható az issue.

**Comment by aboros** [comment]
Lezárom.
