### ISSUE TITLE
Mission / Szervezeti adatok

### ISSUE THREAD

**Issue by reisingerg** [drupalhu/mde#32]
A két szöveg doboz fent nem egy vonalban kezdődik a szöveg.
Szervezeti adatok blokkban nagyobb szöveg sorközt adnék, hogy a két blokk hosszúsága közelítsen egymáshoz, de nem kell sok, mert
Be kellene rakni ide az Alapszabályra hivatkozó gombot is (drótváz alapján).

(Publikus dokumentumok gomb most még nem kell...)

**Comment by reisingerg** [comment]
Link az Alapszabály Google Drive megosztott (megnézhetik) DOC-ra:

https://docs.google.com/document/d/1qSO5amj2VOrgO4w315NrSSalZgPnRmhFMC0n5sZSXVc/edit?usp=sharing

**Comment by csakiistvan** [comment]
Jelzek ha lehet tesztelni
