### ISSUE TITLE
Mission szöveg javítás

### ISSUE THREAD

**Issue by zsofimajor** [drupalhu/mde#38]
Ezt a mondatot:
A magyarországi Drupal közösség a Drupal tartalomkezelő rendszer első verzióinak megjelenést követően kezdett el szerveződni, így több, mint 10 éves múltra tekinthet vissza.
-->
A magyarországi Drupal közösség a Drupal tartalomkezelő rendszer első verzióinak megjelenését követően kezdett el szerveződni, így több, mint 10 éves múltra tekinthet vissza.

(jav: megjelenést-megjelenését)

Ill. ezt:
Szakmai rendezvények szervezése, támogatása és promótálása
-->
Szakmai rendezvények szervezése, támogatása és promotálása

(ez utóbbiban egy nyelvtanzseni adhat mondjuk tanácsot, nekem a rövid o-s verzió jobban bejön)

**Comment by csakiistvan** [comment]
Jelzek ha lehet tesztelni
