### ISSUE TITLE
Projekt logók

### ISSUE THREAD

**Issue by aboros** [drupalhu/mde#4]
A projektek részben minden projekthez jó lenne egy logó vagy valami ikonikus képecske. 

A DUGnak úgy tudom nincs saját logója és a mostani MDE logo az pedig a Drupal Hétvége logoja. A másik két projekt logóját be kell szerezni.

**Comment by reisingerg** [comment]
Igen, jelenleg nem rendelkezik minden elemünk saját arculattal, de ezen is dolgozni kívánunk, így az MDE / DH / DUG hármas jelenleg azonos arculatot, logót használ.

MDE / DH / DUG logo: http://5net.hu/sites/default/files/Drupal-HU-logo.png
IronCamp logo: http://5net.hu/sites/default/files/ironcamp_logo.png
Drupalaton: https://www.dropbox.com/s/1q2g2s4tnh7w1gd/Drupalaton_bag.pdf?dl=0
