### ISSUE TITLE
Padding töréspont(ok) után

### ISSUE THREAD

**Issue by reisingerg** [drupalhu/mde#40]
Töréspont (tablet / mobil) után a Projektek blokkban nagyobb padding kell a 2 soros elemek között, most összeérnek.

Töréspont után (tablet / mobil) a "szervezeti adatok" alcím fölött kellene padding.

Töréspont után (tablet / mobil) "az egysület rendes tagjainak kötelessége" alcím fölött kellene padding.

Töréspont után (tablet / mobil) "Csatornáink" blokk elemei nem törnek szépen, logikusan, egymásra tapadnak.

**Comment by csakiistvan** [comment]
Jelzek ha tesztelhető
