### ISSUE TITLE
Milyen előnyöket biztosít a tagság rész problémái

### ISSUE THREAD

**Issue by aboros** [drupalhu/mde#5]
Az itt található két lista egymással is és a listaelemek is összefolynak, nehezen olvasható emiatt ez a rész.

**Comment by aboros** [comment]
Nekem idegen ez az egész szekció a hangulattól amit szeretnék elérni. Túl hivatalos, bürökratikus szöveg. Az alapszabályban megtalálható, azt minden tag elolvassa mielőtt belép. Szerintem erre a részre nincs szükség, helyette az alapszabályt linkelném be, amire most egy link se mutat a weboldalon.

**Comment by reisingerg** [comment]
Alapvetően egyetértek, de egyenlőre hagyjuk bent.
Vannak kétségeim, hogy mindneki elolvassa-e az Alapszabályt belépés előtt... :)
Az MDE tagság előnyeiről lesz egy workshopunk, annak eredményét javasolnám iderakni, de ez összetettebb ennél most.

Alapszabály GDrive linkje, DOC formátumban, azaz csak a tartalma mérvadó, nem ez a hivatalos verzió, viszont nincsenek benne érzékeny, személyes adatok és a tartalma megegyezik:
https://docs.google.com/document/d/1qSO5amj2VOrgO4w315NrSSalZgPnRmhFMC0n5sZSXVc/edit?pli=1
