### ISSUE TITLE
A Dockerfile -t erdemes lenne kulon rakni

### ISSUE THREAD

**Issue by gyulaweber** [drupalhu/mde#54]
Amikor a build elindul, akkor default a Docker client elkuldi a daemon -nak a teljes context -et, ami itt az osszes fajl abban a konyvtarban, ahol a Dockerfile van.  Ehhez szeretnek ket megoldast javasolni:
1. Erdemes lenne egy kulon konyvtarba rakni a Dockerfile -t, ahova csak azok kerulnek, amiket el kell tudni erni a build folyaman
2. .dockerignore -be rakni azokat, amelyek nem kellenek a build -hez

Ezzel megelozheto, hogy kesobb ha tobb anyag kerul ide, feleslegesen lassitsa a build -et.

ref.: http://stackoverflow.com/questions/26600769/build-context-for-docker-image-very-large

Remelem tudtam segiteni ;)

**Comment by tanarurkerem** [comment]
Köszi, külön raktuk és hozzáadtam egy build.sh-t ami a Gemfile-t bemásolja a Dockerfiel mellé.

pp
