### ISSUE TITLE
Elnökségi tagok fotói túl kicsik

### ISSUE THREAD

**Issue by aboros** [drupalhu/mde#6]
Jelenleg mindenkinek a drupal.hu profilképe szerepel a weboldalon, ami túl kicsi. A drótváz alapján 150x150 pixeles, lekerekített képek legyenek.

**Comment by csakiistvan** [comment]
@aboros ehhez kértél, és több mindenkitől kaptál isfotókat ugye? azok megvannak?

**Comment by aboros** [comment]
igen, azokat előkeresem és a többiektől pedig begyűjtöm.

**Comment by tanarurkerem** [comment]
repoba mehetne, mert ugye egy ilyet az issue kezelőbe kéne tölteni, de ide nem lehet.. vagy igen? (wiki talán)

**Comment by csakiistvan** [comment]
lehet
<img width="701" alt="screen shot 2015-09-02 at 07 49 24" src="https://cloud.githubusercontent.com/assets/2457274/9623859/27ae03e8-5147-11e5-8a00-d0137030034b.png">

**Comment by csakiistvan** [comment]
Mielőtt repóba felmenne optimalizáljuk a https://tinypng.com/ on pls

**Comment by tanarurkerem** [comment]
vakvagyok vaz, gombot kerestem... lololo:)

**Comment by reisingerg** [comment]
Mondjátok kié hiányzik vagy nincs meg, intézem...

**Comment by aboros** [comment]
Írok mindenkinek ma és begyűjtöm. Magamhoz rendeltem az issut.

**Comment by Sweetchuck** [comment]
https://en.gravatar.com/davidandor

**Comment by aboros** [comment]
köszi Sweetchuck, de ez is csak 80x80px (https://secure.gravatar.com/avatar/f5379056e5acd03d4415b9997b20875f)

**Comment by Sweetchuck** [comment]
Igen 80 pixeles amikor rákattintasz, de magán a weboldalon nem az jelenik meg.
https://secure.gravatar.com/avatar/f5379056e5acd03d4415b9997b20875f?size=400px

**Comment by reisingerg** [comment]
Az enyém ha nem lenne meg: http://5net.hu/sites/default/files/ant_images/Reisinger-G%C3%A1bor.jpg

**Comment by reisingerg** [comment]
Akkor összefoglalva:

RG: http://5net.hu/sites/default/files/ant_images/Reisinger-G%C3%A1bor.jpg
Andor: https://secure.gravatar.com/avatar/f5379056e5acd03d4415b9997b20875f?size=400px
Zsófi: https://files.slack.com/files-pri/T035YDTC2-F0AAQE7BK/14879811573_1c2a2d8d3d_o.jpg
TG: https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/3/005/084/0fc/16c3067.jpg

Egyébként úgy látom Drupalaton oldalon fent van mindenki képpel, lehet azokat raknám be:

Zsófi
Aboros
Resi
CSG
Pónya Péter
Andor

Én Drupalaton fotókra szavaznék!

**Comment by csakiistvan** [comment]
Zsófi, https://dl.dropboxusercontent.com/u/743951/14879811573_1c2a2d8d3d_o.jpg
