### ISSUE TITLE
css a legfrissebb?

### ISSUE THREAD

**Issue by tanarurkerem** [drupalhu/mde#61]
Amikor #54 miat lefuttatam a compas-t ezt tette a style.css-el:

```
+#projects .project-item img {
+  margin: 0 auto 25px;
+}
+
```

**Comment by aboros** [comment]
Hm. Fura. Én up-to-date vagyok és ha `compass compile` -t futtatok, semmi nem változik. Mondjuk nem dockerrel csinálom, hanem a globális compassommal. (1.0.3)

**Comment by tanarurkerem** [comment]
figy, aki reszeli a css-t annak azért úgy gondolom tudnia kéne, hogy kell-e az a szabály avagy sem. :D De ha Te se tudod akor ok, de emlékeim szerint volt valami para a project képekkel... talán ez volt az.

pp

**Comment by aboros** [comment]
Jahogy ez volt a kérdés? :D Akkor a válasz az hogy kell. De nem én reszeltem a csst amúgy :) Szóval mégegyszer: kell az.
