### ISSUE TITLE
http://mde.drupal.hu rossz link

### ISSUE THREAD

**Issue by tompagabor** [drupalhu/mde#62]
Az oldalon ez a link van feltüntetve: http://mde.drupal.hu
De valójában az http://egyesulet.drupal.hu/ a valódi link.
Ezt cserélni kell

**Comment by zsofimajor** [comment]
Ez már egyszer megjavult: https://github.com/drupalhu/mde/issues/53

(közben rájöttem, hogy nem az alatta lévő link a rossz, hanem a szöveg a linken. Bocs, ignore.)
