### ISSUE TITLE
Elnökségi és FEB tagok cseréje a tisztújítás után

### ISSUE THREAD

**Issue by tompagabor** [drupalhu/mde#65]
Új elnökségi tagok: 
 - Ertl-Bakos Balázs
 - Oroszvári Péter

Leköszönő elnökségi tagok:
 - Segesvári Dávid
 - Boros Ádám

Új FEB tag:
 - Czövek András

Leköszönő FEB tag:
 - Csonka Gergely

Az új tagokhoz szükséges tartalom:
 - email cím
 - fotó

Opcionális tartalom az új tagokhoz:
 - twitter fiók

**Comment by BaluErtl** [comment]
Azt hiszem, ezt a 2+ éves tiketet már lezárhatjuk, nyitok újat a nemrég aktuálisnak.
