### ISSUE TITLE
Acquia Hosting tulajdon jog

### ISSUE THREAD

**Issue by csakiistvan** [drupalhu/mde#77]
Jelenleg az Acquia Hosting-on van a drupal.hu.
Az Acuia Hostin-on a fiók tulajdonosa Boros Ádám.
Ádám intézte el, hogy az ingyenes "Drupal community website hosting" lehetőséget használhassuk. Egyesület még sehol nem volt akkoriban. 

Különösebben ez őt nem érdekli, de azért jelezte, hogy jó lenne ha nem az ő nevén menne a projekt, és átvenné mondjuk az MDE.

* Acquia Hosting [login](https://accounts.acquia.com/sign-in?site=insight)
* Acquia Hosting [Drupal Hungary](https://cloud.acquia.com/a/applications/87e5fc5e-1081-5684-fd4b-e32058f6ca49)

---

1. Elsőként regisztrálni kéne az egyesulet@drupal.hu -val egy fiókot
2. Aztán megkérni Ádámot, hogy nyomja meg a gombot.

![Image](https://user-images.githubusercontent.com/591103/220207073-66e83cc9-ae91-48dd-be2e-9d8120d3ce23.png)

**Comment by Pandelon** [comment]
ezt teljesen elvetettük?
