### ISSUE TITLE
Belépési nyilatkozatok linkjei

### ISSUE THREAD

**Issue by aboros** [drupalhu/mde#8]
A kétféle belépési nyilatkozatot három formátumban felajánlani hat gombot eredményez. Nem elegáns és nem is haszos. Legyen helyette mindkét nyilatkozat elérhető nyilvánosan az MDE google dokumentumai között és oda linkeljünk. Mindenki kinyomtathatja vagy letölti amibe akarja.

**Comment by tanarurkerem** [comment]
Szerintem tökre nem zavaró...
Én meghagynék egy egyklikkes verziót is...
... mi lenne, ha lenne egy letölthető pdf és belinkelnénk magát a google doksit, mert akkor onnan úgy exportálják ahogy akarják?

**Comment by reisingerg** [comment]
Jogi személyek Belépési Nyilatkozat:
https://docs.google.com/document/d/14kJTMQwvwJ2Fll61oLpsaXFF8m1AboG7CaXQTWF4Kz8/edit?usp=sharing

Természetes személyek Belépési Nyilatkozata:
https://docs.google.com/document/d/1Lv0_FkSUGkRfx6rkMN1-RiUfarZPBqNPu405iW0bsdU/edit?usp=sharing
