### ISSUE TITLE
Fejléc kép véglegesítése

### ISSUE THREAD

**Issue by aboros** [drupalhu/mde#9]
Jelenlegi fejlécképpel kapcsolatban felmerült probléma: az emberek nagy része nem is magyar. Felmerült az igény, hogy lehetőleg olyan fejléckép legyen, ami a magyar közösséget mutatja. Akinek van konkrét javaslata kérem ne tartsa magában!

**Comment by reisingerg** [comment]
Bár nem fedi teljesen a HU közösséget, de szegedi DDD-ről: https://www.flickr.com/photos/29978062@N04/13443854774/in/album-72157642837153565/

**Comment by csakiistvan** [comment]
Ez még vita kérdése, vagy akkor melyik lesz?

**Comment by reisingerg** [comment]
Nekem nincs bajom a mostanival, ha tudjuk kicsit jobban pozícionálni és még több embert mutatni rajta.
Ha kell, akkor keresgélek még képeket. SB szempontjából szerintem bármelyik mehet, aztán max cseréljük :)
